# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f87163b383a221a4769691dadab5fd7cd24e9432e3bb99887fe38e01537034d287348446335717d5bc6ef18003695425b0bb2a5b3506536cc0b5900897a1e53d
  
  FACEBOOK_KEY: 1793986637490199
  FACEBOOK_SECRET: 0b221eb0e71bcd2f420d744c910dbd14

  TWITTER_KEY: 3I3X24zPyIUx9wfHsNEKFoSMm
  TWITTER_SECRET: MusPEVhBRNE6QXeKKEU9rcbql7zpPrikenFKQXsSh504UxjGKX
test:
  secret_key_base: c9fa8bb220aa710ecdf41cbfc1ccc286b6975357603025b956c996b569ff7fd556e7023bd72e7510da7698e2165722b29ffa9996c85a6dd044dd0cd5746c44ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
